---
- name: Install Composer global packages.
  shell: >
    COMPOSER_HOME={{ composer_home_dir }}
    {{ composer_exec }} global require {{ item.name }}:{{ item.release | default('@stable') }} --no-progress
    creates={{ composer_home_dir }}/vendor/{{ item.name }}
  with_items: composer_global_packages

- name: Add Composer home dir to $PATH.
  template:
    src: composer.sh.j2
    dest: /etc/profile.d/composer.sh
    owner: root
    group: root
  when: composer_add_to_path
